### ISSUE TITLE
Binder support

### ISSUE THREAD

**Issue by nathanweeks** [GMOD/jbrowse-jupyter#19]
Is it possible (and not too much effort) to adapt this repo so it runs out-of-the-box with [Binder](https://mybinder.org/)? Or is that not feasible/recommended due to technical or other limitations?

**Comment by nathanweeks** [comment]
Hi @teresam856 , thanks for the info info. I'm admittedly not experienced with Colab; it seems to provide more computing power than Binder, though it also requires a Google account to use.

With Binder, if all dependencies are specified in [supported language-/software-package-specific formats](https://mybinder.readthedocs.io/en/latest/reference/index.html), the container image that is built at launch time (and cached for later reuse) will have the complete software environment & be ready-to-go for the end user.

The jbrowse-jupyter dependency [jupyter-dash](https://github.com/plotly/jupyter-dash) package has a "launch binder" badge in its README.md, so I'd surmise it may be technically possible to adapt jbrowse-jupyter for binder?

But getting jbrowse-jupyter working with Binder is admittedly not a super-high priority if the current Colab setup works well for the use cases potential end users care about.

**Comment by teresam856** [comment]
@nathanweeks Just added a link to binder on our readme https://github.com/GMOD/jbrowse-jupyter. It is making use of our requirements.txt. Let me know if this works for your use case :)

**Comment by nathanweeks** [comment]
@teresam856 Thanks! The binder link launches a notebook with dependencies installed. When the notebook launches, a box containing the following message (+ build & cancel buttons) is displayed:
> Build Recommended
> JupyterLab build is suggested:
> jupyterlab-dash needs to be included in build
Clicking "build" and waiting a few minutes for the build to finish (at least until the `node` processes that were launched have stopped), then clicking through the 5th cell (with `launch(new_conf, port=3003)`), the resulting output below the cell is a box with "127.0.0.1 refused to connect".

Did I make a mistake in the process?

**Comment by teresam856** [comment]
No, it seems like there may be an issue with jupyterlab and the jupyter widgets extension . Will have to investigate further to see if there is a fix to generate a new binder link. Apologies.
