### ISSUE TITLE
werkzeug > 2.0.3 throws errors

### ISSUE THREAD

**Issue by LeoWelter** [GMOD/jbrowse-jupyter#36]
see https://github.com/plotly/dash/issues/1992

I ran into the same issue when installing jupyter-jbrowse.
Its more a dash issue, but just wanted to report here that downgrading to 2.0.3 works

**Comment by teresam856** [comment]
@LeoWelter thank you for reporting this. A patch to the jupyter-jbrowse is coming soon.

**Comment by teresam856** [comment]
Just released jbrowse-jupyter v1.2.2 with  werkzeug pinned to v2.0.3 https://github.com/GMOD/jbrowse-jupyter/blob/main/requirements.txt#L4. 
Let me know if there are any other issues, and thanks again for reporting this.

Note: closing this issue.
