### ISSUE TITLE
Colab example, reason for using github for pip install?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-jupyter#60]
I managed to get the colab example running, but it was unclear what purpose is using

```
!pip install git+https://github.com/GMOD/jbrowse-jupyter.git@main
```

Can jbrowse-jupyter get re-published to pip and remove this need to modify the colab notebook explicitly

**Comment by teresam856** [comment]
Can you point me to where you are seeing this? I just checked on main, and it has pip install jbrowse-jupyter
no the github link

**Comment by cmdcolin** [comment]
sorry I didn't describe it further...I visited 

https://colab.research.google.com/github/GMOD/jbrowse-jupyter/blob/main/browser.ipynb

it contains

```
!pip install jbrowse-jupyter
```

but then, performing "Run all" makes an error

```
AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _dep_map(self)
   3015         try:
-> 3016             return self.__dep_map
   3017         except AttributeError:

19 frames

AttributeError: _DistInfoDistribution__dep_map


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)

AttributeError: _pkg_info


During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in _get(self, path)
   1609 
   1610     def _get(self, path):
-> 1611         with open(path, 'rb') as stream:
   1612             return stream.read()
   1613 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/Flask-1.1.4.dist-info/METADATA'
```
![Screenshot from 2022-10-14 11-58-58](https://user-images.githubusercontent.com/6511937/195911425-60cbbbf7-85a2-47cf-b1ad-c1de9cc9f86b.png)


then I saw in the readme that it says

```
You can open this browser.ipynb in colab [here](https://colab.research.google.com/github/GMOD/jbrowse-jupyter/blob/main/browser.ipynb) Note: to install the package in colab you can use this command. In a new cell above the import statement

!pip install git+https://github.com/GMOD/jbrowse-jupyter.git@main
```

I interpreted this to mean "replace !pip install jbrowse-jupyter with   !pip install git+https://github.com/GMOD/jbrowse-jupyter.git@main" and so I did that, and then redid "Run all", and it displayed the embedded lgv's successfully with no errors after that. I then thought that this implies that if the package got republished, then it would not need to install from github in the colab?

**Comment by teresam856** [comment]
I see how that can be confusing. I think the comment on the readme is stale, I will remove that line. I had the `!pip install git+https://github.com/GMOD/jbrowse-jupyter.git@main` before Jbrowse-jupyter was released, so this was just so that we could start testing the package prior to its formal release in pypi. 

The issue you see there when running run all in colab, is that sometimes pip may be funky. This issue is related https://github.com/gradio-app/gradio/issues/870. It is an issue that @scottcain  has also seen. I can resolve it by pip installing flask right after to avoid any issues.

**Comment by cmdcolin** [comment]
I see, I am not exactly sure what the best course of action is! If adding an extra pip helps avoid the error, might be worth it, until error is otherwise resolved upstream somehow

**Comment by teresam856** [comment]
Okay, I think I will add that. I think avoiding errors is best if others will be running this notebook.

**Comment by scottcain** [comment]
Yeah, I think having a cell that has this right after the jbrowse install is a reasonable thing to do:
```
#in Google Colab, it seems that we can't use Flask 2.1.3, so we'll force it to use 1.1.4
#!pip install Flask==1.1.4
```

**Comment by teresam856** [comment]
Added here https://github.com/GMOD/jbrowse-jupyter/pull/62
