### ISSUE TITLE
Move pytest to tests_require in setup.py

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-jupyter#61]
Looking at `setup.py`, it looks like it uses `requirements.txt` for its `install_requires`. However, `requirements.txt` includes `pytest`, which is needed to run the tests, but isn't a dependency for the package to install. Looking at the guide [here](https://python-packaging.readthedocs.io/en/latest/testing.html), it seems like `pytest` should be in `tests_require` instead of `install_requires`.

**Comment by teresam856** [comment]
Yeah I can remove the dependency on pytest from the requirements.txt and add it to the setup.

**Comment by teresam856** [comment]
@garrettjstevens https://github.com/GMOD/jbrowse-jupyter/pull/62
