### ISSUE TITLE
CHM13 genome configuration

### ISSUE THREAD

**Issue by arpanda** [GMOD/jbrowse-jupyter#72]
Is there any config setting for CHM13-V2.0 ? I did the following to load the CHM13 genome. 

```
chm13 = create('LGV')
chm13.set_assembly("https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz", aliases=["chm13"])
chm13.set_location("10:100..350")
chm13.set_default_session(['df_track_id'], False)
new_conf = chm13.get_config()
launch(new_conf, port=3013)
```
but the loading is slow. 

Thanks
Arijit

**Comment by cmdcolin** [comment]
it looks like there is no fasta index for this file e.g. https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz.fai does not exist (interestingly https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz.gzi does exist, both the fai and gzi are needed for bgzip indexed fasta)

you can maybe use https://jbrowse.org/genomes/CHM13/fasta/chm13v2.0.fa.gz instead, we created this for testing purposes but should be somewhat stable and it has fai and gzi

**Comment by cmdcolin** [comment]
(there is a gfftabix here also https://jbrowse.org/genomes/CHM13/gff/chm13v2.0.gff.gz)

**Comment by arpanda** [comment]
Thanks @cmdcolin.
 I can browse the chm13 genome now. is there any aliases file for chm13 in that link?

**Comment by cmdcolin** [comment]
might be able to use https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.chromAlias.txt as alias,  hs1 from ucsc is same as chm13v2.0
